### ISSUE TITLE
add default values to help

### ISSUE THREAD

**Issue by rmnldwg** [hamdanal/rich-argparse#1]
Hey! Really nice extension you have made here, thanks a lot 👍

In the example screenshot in the `README` I see a default value being displayed at the end of the help text. However, when I used the `RichHelpFormatter`, the default values did not show up at the end of the respective help texts.

Is there an easy way to add it to your formatter?

**Comment by hamdanal** [comment]
Glad you like it.

The default value displayed in the screenshot for the option `--bool, --no-bool` comes from the use of `argparse.BooleanOptionalAction` (python 3.9 and above) and has nothing to do with the formatter.

For other [types of actions](https://docs.python.org/3/library/argparse.html#action), you can display the default value in the help by using [`%(default)s` in the help string](https://docs.python.org/3/library/argparse.html#help).

If you want to display the default values of all the arguments, there is `argparse.ArgumentDefaultsHelpFormatter` in argparse that does exactly that -- you can create an empty formatter that inherits from both formatters and use it instead.
```python
class RichArgumentDefaultsHelpFormatter(RichHelpFormatter, argparse.ArgumentDefaultsHelpFormatter): ...
```

**Comment by rmnldwg** [comment]
Oh wow, that's nice and easy 😅

I didn't know about `argparse.ArgumentDefaultsHelpFormatter`, thanks a lot!
