### ISSUE TITLE
Brackets around optional positional args and options are a different color

### ISSUE THREAD

**Issue by dbohdan** [hamdanal/rich-argparse#100]
I get a help message like this from the code below.

![screenshot](https://github.com/hamdanal/rich-argparse/assets/3179832/8a0d8f0e-569a-4a09-ba2a-d03572c22c68)

The square brackets around the optional positional argument are red, while those around the options are not. I am not sure whether this is intentional, but it looks incorrect. I would expect all sets of brackets to be the same color (default, not red in this example).

```python
import argparse
from rich_argparse import RichHelpFormatter


def main() -> None:
    parser = argparse.ArgumentParser(
        formatter_class=RichHelpFormatter,
    )

    RichHelpFormatter.styles["argparse.args"] = "red"
    parser.add_argument(
        "positional",
        nargs=argparse.OPTIONAL,
    )
    parser.add_argument(
        "--option",
    )

    args = parser.parse_args()


if __name__ == "__main__":
    main()
```

**Comment by hamdanal** [comment]
This is not "intentional" but rather a known issue. I ignored it because it requires some tedious metavar parsing and special casing argparse internals. It gets more complicated with other `nargs` values like `argparse.ZERO_OR_MORE`, `argparse.ONE_OR_MORE` and others.
This is the the second request to fix this issue so maybe its time to reevaluate my position on the topic.

**Comment by dbohdan** [comment]
Sorry, I missed the first issue when I opened mine: https://github.com/hamdanal/rich-argparse/issues/59. 

If this is difficult to fix, and especially if the fix would be fragile, maybe it is not worth it. (At least not until argparse is fixed.) A note in the readme explaining the behavior may suffice. The person who opened the first issue was also confused about whether the difference was intentional, and a note would help with such confusion. I'd add a note even if you intended to fix this later.

**Comment by hamdanal** [comment]
> Sorry, I missed the first issue when I opened mine: #59.

No worries. Yes this is the one.

> If this is difficult to fix, and especially if the fix would be fragile, maybe it is not worth it. (At least not until argparse is fixed.) A note in the readme explaining the behavior may suffice. The person who opened the first issue was also confused about whether the difference was intentional, and a note would help with such confusion. I'd add a note even if you intended to fix this later.

I might be able to handle the positional arguments brackets without hitting the edge cases of argparse. However adding a style for the symbols as requested in the linked issue is more complicated.
