### ISSUE TITLE
allow newlines in `"version"`

### ISSUE THREAD

**Issue by nschloe** [hamdanal/rich-argparse#111]
When using

```python
parser = argparse.ArgumentParser(
    description="foo",
    # formatter_class=argparse.RawTextHelpFormatter,
    formatter_class=RichHelpFormatter,
)

parser.add_argument(
    "--version",
    "-v",
    action="version",
    version=get_version_text(),
    help="display version information",
)

def get_version_text():
    return "a\nb\n\n\nc"
```

newlines in the output are suppressed. Would be great to allow for those.

**Comment by hamdanal** [comment]
Thanks for the issue.
This behavior comes from the argparse implementation of the version action `_VersionAction` which calls the formatter to render the version text, it is not part of rich-argparse I am afraid. If you use `RichHelpFormatter` or `argparse.HelpFormatter`, all whitespace in the text will be normalized to a single space character before it is printed. You can refer to the argparse documentation https://docs.python.org/3/library/argparse.html#formatter-class for more information.

If you don't want the formatter to mess up already formatted text, you can use the `RawTextRichHelpFormatter` class instead.

Alternatively, if you pass the version as a rich renderable like a `Text` object, rich-argparse skips the argparse normalization of whitespace and keeps existing newline characters.

Note that runs of more than three newline characters are always truncated to two even with a rich renderable.

```python
import argparse
from rich_argparse import RichHelpFormatter
from rich.text import Text

def get_version_text():
    return "a\nb\n\n\nc"

parser = argparse.ArgumentParser(description="foo", formatter_class=RichHelpFormatter)
parser.add_argument(
    "--version",
    "-v",
    action="version",
    version=Text(get_version_text()),
    help="display version information",
)
parser.parse_args()
```
For example this code produces:
```console
$ python main.py --version
a
b

c
```
