### ISSUE TITLE
How to disable styles?

### ISSUE THREAD

**Issue by hamdanal** [hamdanal/rich-argparse#121]
### Discussed in https://github.com/hamdanal/rich-argparse/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **bulletmark** May 17, 2024</sup>
I have a number of Python CLI programs, some of which use subparsers, so I thought I'd try this to see how it looks. However, I find that it interprets rich styles in my code which I did not intend. E.g. it seems I have commonly written "applications[s]" to indicate one or more applications but I am getting a strike-through on all those lines. How can I disable style interpretation?

I already tried `RichHelpFormatter.highlights.clear()` and `RichHelpFormatter.usage_markup = False` but no difference.</div>

**Comment by bulletmark** [comment]
I added those 2 options but now my help outputs:
```
default="[argparse.default]https://micropython.org/pi/
+                        v2/index.json[/argparse.default]"
```
instead of
```
default="https://micropython.org/pi/v2/index.json"
```

**Comment by hamdanal** [comment]
Yes this is a bug, thanks for the report. I'll fix it and cut a bugfix release shortly.

**Comment by hamdanal** [comment]
Please try version 1.5.1 that I just published

**Comment by bulletmark** [comment]
Yep fixed thanks.
