### ISSUE TITLE
Formatting of arguments applied even within back-ticks (syntax style)

### ISSUE THREAD

**Issue by peterjc** [hamdanal/rich-argparse#141]
This issue relates to the priority in applying the default styles, defined in https://github.com/hamdanal/rich-argparse?tab=readme-ov-file#output-styles as:

```python
{
    'argparse.args': 'cyan',  # for positional-arguments and --options (e.g "--help")
    'argparse.groups': 'dark_orange',  # for group names (e.g. "positional arguments")
    'argparse.help': 'default',  # for argument's help text (e.g. "show this help message and exit")
    'argparse.metavar': 'dark_cyan',  # for metavariables (e.g. "FILE" in "--file FILE")
    'argparse.prog': 'grey50',  # for %(prog)s in the usage (e.g. "foo" in "Usage: foo [options]")
    'argparse.syntax': 'bold',  # for highlights of back-tick quoted text (e.g. "`some text`")
    'argparse.text': 'default',  # for descriptions, epilog, and --version (e.g. "A program to foo")
    'argparse.default': 'italic',  # for %(default)s in the help (e.g. "Value" in "(default: Value)")
}
```

After coming up with https://github.com/peterjc/thapbi-pict/commit/9ef702268331cbeba9e558583e6fa6a97830c0b7 I wonder if this is actually a bug. Consider the following argument:

```python
    subcommand_parser.add_argument(
        "--denoise",  # Named to match sample-tally and pipeline setting
        choices=["unoise-l", "usearch", "vsearch"],
        default="unoise-l",
        help="Choice of read-correction algorithm, default 'unoise-l' for "
        "built-in reimplementation of the Edgar (2016) UNOISE algorithm "
        "using Levenshtein distance. Use 'usearch' or 'vsearch' to call "
        "external tools `usearch -unoise3 ...` or `vsearch --cluster_unoise "
        "...` respectively.",
    )
```

In this example, this part is explicitly a syntax block using backticks, which would be bold by default via the "argparse.syntax" style:

```
`usearch -unoise3 ...`
```

However, in includes a substring which matches the "argparse.args" style (which would be cyan).

# Expected result

I expected to see `usearch -unoise3 ...` all in bold (and not cyan).

# Actual result

We do get bold, but the "-noise3" part within that is recognised as an argument, and formatted in cyan. e.g. Screenshot from prompt3 terminal:

![Screenshot 2024-12-21 at 18 30 16](https://github.com/user-attachments/assets/2e71736d-aad1-4da7-9713-eb1188398cca)

# Workaround

Make the syntax and argument styles the same (as in the commit cited).

**Comment by peterjc** [comment]
Tested with rich==13.9.4 and rich-argparse==1.6.0 under Python 3.12 on macOS in several terminals (some of which do not show bold).

**Comment by hamdanal** [comment]
Yeah this looks ugly, thanks for the issue.
I don't know how to fix it though, suggestions/help welcome.

**Comment by peterjc** [comment]
Looking at the code, I guess it applies all of the regex matches - and thankfully there are only these two at play:

```python
_HIGHLIGHTS = [
    r"(?:^|\s)(?P<args>-{1,2}[\w]+[\w-]*)",  # highlight --words-with-dashes as args
    r"`(?P<syntax>[^`]*)`",  # highlight `text in backquotes` as syntax
]
```

And:

```python
        for highlight in self.highlights:
            rich_text.highlight_regex(highlight, style_prefix="argparse.")
```

So one fix might be some regex magic to stop matching args within backticks (beyond my regex comfort level)?

Or, in that loop applying the highlights consider the location of the matches to avoid double styling?

Or, apply the backtick detection and styling "manually" in Python code, and continue with the regex approach for the args on the text determined to be outside any backticks?

Sadly I don't see an easy fix either.

**Comment by hamdanal** [comment]
I think I figured out a solution in #142. If I "OR" the two regular expressions, they seam to not overlap anymore.

Could you please test it on your application before I merge it? You don't need to install anything, add this line to your code:
```python
RichHelpFormatter.highlights = [r"`(?P<syntax>[^`]*)`|(?:^|\s)(?P<args>-{1,2}[\w]+[\w-]*)"]
```

**Comment by peterjc** [comment]
Perfect - that works nicely, and retains the original styling you intended. Thanks!
