### ISSUE TITLE
Add Poetry installation instructions

### ISSUE THREAD

**Issue by nilsso** [hamdanal/rich-argparse#2]
Firstly thanks for putting this together; it works perfectly :+1:.

Since the repo has a nice `pyproject.toml` it's very easy to include into a Poetry based project, and I just want to propose adding additional installation instructions to the readme:

> ## Installation
>
> Copy the file `rich_argparse.py` to your project, or...
>
> ### Poetry
>
> ```bash
> poetry add git+https://github.com/hamdanal/rich-argparse#main
> ```

(Sorry that this isn't a full pull-request; figured its a small enough change.)

**Comment by hamdanal** [comment]
Hi, I added the pyproject.toml file with the intention of releasing to pypi if this module gets some attention. I think it is time to do so. After that, the installation would become the simple `pip install` / `poetry add`. As of now, I haven’t tested the pyproject.toml so I cannot recommend using it. The module will hopefully be available on pypi very soon and I will update the readme. Thanks for the suggestion.

**Comment by hamdanal** [comment]
The project is now on PyPI and the README is updated to reflect the ability to use pip or other package managers for the installation. Thank you for the ticket.
