### ISSUE TITLE
[Feature Request] Showing defaults

### ISSUE THREAD

**Issue by michelcrypt4d4mus** [hamdanal/rich-argparse#27]
Seeing default values in the help is very useful. `argparse` ships with `ArgumentDefaultsHelpFormatter` but `ArgumentDefaultsHelpFormatter` is annoying because it shows you `default: None` (or `False`) for everything, including things where the default is obviously `None`/`False`. A workaround I found a few places and have been using is something like this:

```python
# Class to enable defaults to only be printed when they are not None or False
class ExplicitDefaultsHelpFormatter(ArgumentDefaultsHelpFormatter):
    def _get_help_string(self, action):
        if 'default' in vars(action) and action.default in (None, False):
            return action.help
        else:
            return super()._get_help_string(action)
```

which patches `ArgumentDefaultsHelpFormatter` to only show explicitly set defaults. Is this something `rich-argparse` could support?

**Comment by hamdanal** [comment]
It is already supported. You just need to add `RichHelpFormatter` as another base class to your formatter class. If it doesn't work it certainly is a bug.

**Comment by michelcrypt4d4mus** [comment]
Thanks; the defaults do show up when I do the multi-inheritance:

```python
class ExplicitDefaultsHelpFormatter(RichHelpFormatter, ArgumentDefaultsHelpFormatter):
    def _get_help_string(self, action):
        if 'default' in vars(action) and action.default in (None, False):
            return action.help
        else:
            return super()._get_help_string(action)
```

maybe they should be shown by default though, without multi-inheritance / with some kind of styling?

**Comment by hamdanal** [comment]
I don't think this should be the default and it is not "styling" issue as it is a formatter behaviour. Also subclassing works well (this is how argparse formatting works, no options, only subclasses) so I will not work on this, sorry.
