### ISSUE TITLE
Formatting error when printing via rich.console

### ISSUE THREAD

**Issue by kotfu** [hamdanal/rich-argparse#54]
When printing the results of  `format_help()` from an argparser that uses `RichHelpFormatter()` as a formatter, the output is not formatted correctly if those results are printed using `rich.console.Console`. I've created a program which reproduces this problem:
```
# reproduce a formatting bug in RichHelpFormatter()

import argparse
import rich_argparse
import rich.console

console = rich.console.Console(markup=False, emoji=False, highlight=False)
prsr = argparse.ArgumentParser(
    prog="config",
    description="Edit or show the location of the user configuration file.",
    formatter_class=rich_argparse.RichHelpFormatter,
)
prsr.add_argument(
    "action",
    choices=["edit", "file", "convert"],
    help="""'edit' edits the configuration file in your preferred editor.
            'file' shows the name of the configuration file.
            'convert' writes a new .toml configuration file with the same settings as the old .ini configuration file.""",
)

console.rule("printing help with print()")
print(prsr.format_help())

console.rule("printing help with rich.console.print")
console.print(prsr.format_help())
```

Here's a screenshot of the output:
<img width="1134" alt="screenshot" src="https://user-images.githubusercontent.com/218536/219834080-4157b43b-36c5-41e2-828c-ec08e0d48c13.png">

Note that when the output is printed using `console.print(prsr.format_help())` the help text for the single positional argument does not wrap correctly.

My current (untested) hypothesis is that this has something to do with having nested `rich.console` objects. The current implementation of `format_help()` uses the `.capture()` context manager to collect the output before returning.

**Comment by hamdanal** [comment]
Thanks for the extra context.

> Note that when the output is printed using `console.print(prsr.format_help())` the help text for the single positional argument does not wrap correctly.

This has to do with your console trying to wrap the output to fit the console width (the console width is by default set to the width of your terminal). Note that the formatter's output is wrapped by the formatter itself, not by the internal console and shouldn't be wrapped by the external console. This is how argparse formatters work (`HelpFormatter` wraps everything, `RawDescriptionHelpFormatter` wraps everything except the description, `RawTextHelpFormatter` doesn't do any wrapping).
To solve your issue, you have two solutions:
1. use the built-in `print` (as you saw with the first part of your example): `print(prsr.format_help())`
2. tell your console to not wrap the formatter output as this is handled by the formatter itself: `console.print(prsr.format_help(), soft_wrap=True)`

> My current (untested) hypothesis is that this has something to do with having nested `rich.console` objects. The current implementation of `format_help()` uses the `.capture()` context manager to collect the output before returning.

This has nothing to do with the internal console, it just return the text as a string. The same wrapping issue would happen if you **console print** any long text that contains new lines and leading spaces. If you follow solution 2 above, your problem will be solved.

I'll close this issue as no action has to be taken in `rich_argparse`. Feel free to continue the discussion if you have more questions.
