### ISSUE TITLE
`RichHelpFormatter.styles["argparse.prog"] = "bold red"` should set prog name color in `-v` aswell.

### ISSUE THREAD

**Issue by pcroland** [hamdanal/rich-argparse#77]

**Comment by hamdanal** [comment]
By `-v` I think you mean when asking for the version of the program using `action=version`? The version action is rendered using the same code path as the description and epilog. Do you think these should also set the `argparse.prog` style as well? It is not possible to set the style in one and not the others.

**Comment by pcroland** [comment]
Yes, It would give a more consistent look.

**Comment by pcroland** [comment]
Oh, nevermind, you have to provide a `version=` string for `-v`/`--version` anyway, and you can add the same color there.

**Comment by hamdanal** [comment]
I am glad you found a way to make it work. I think we should keep the issue open, we should at least to add a documentation about the `--version` action styling. Happy to accept a PR if you feel like it.
